### ISSUE TITLE
THREE.Math shadows global Math object 

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#1]
Currently, THREE.Math is mapped into a local var Math object. This means expressions like Math.PI cause reference errors in a final build of THREE.js in areas where code uses the THREE.Math module.

How do you guys think this problem should be solved?

**Comment by kumavis** [comment]
Ah thats an interesting edge case. some ideas:

* in this case, rewrite the variable name to `ThreeMath`:
```js
var ThreeMath = require('./math.js')
```
* change the src to `THREE.Math` to inherit from `Math`:
```js
NewMath = Object.create(Math)
NewMath.PI //=> 3.141592653589793
```

In general I would avoid modifying the source for this conversion project, so the first suggestion is preferred.

**Comment by coballast** [comment]
The first option shouldn't be too difficult to implement, so that's what I think I'll do.

**Comment by coballast** [comment]
Did as you suggested. Examples now fail for completely different reasons. Hooray!
