### ISSUE TITLE
THREE is undefined.

### ISSUE THREAD

**Issue by kumavis** [coballast/threejs-browserify-conversion-utility#12]
`Three.js` adds properties to THREE, but does not define it. It is currently being defined in `ThreeGlobals.js`

**Comment by coballast** [comment]
Ah yes. Currently I just manually move it over to Three.js (and remove the browserify support check)

**Comment by coballast** [comment]
I plan to just manually change this, as adding code to fix it automatically is far more effort than it's worth. Closing.

**Comment by kumavis** [comment]
We should keep track of necessary manual steps then. Add as instructions to readme?

**Comment by coballast** [comment]
Sure. I will add them.
