### ISSUE TITLE
Reuse of temporary instances

### ISSUE THREAD

**Issue by HMUDesign** [coballast/threejs-browserify-conversion-utility#19]
This issue is related to circular dependencies and it appears many times. It seems to be an optimization to prevent creating a new Vector3 (or other core class) each time the function is called. If there is indeed a significant performance hit that cannot be fixed by optimizing Vector3, then perhaps add a function to Vector3 to return an unused vector3 which is released later?

```
Foo.prototype.bar = function() {
    var vector = new Vector3();
    return function() {
        // some data which reuses vector repeatedly.
    };
}();
```

**Comment by coballast** [comment]
@HMUDesign Please keep in mind that the code on the browserify repo is not the latest dev branch. One thing I changed is that it instantiates those instances lazily, in mrdoob/three.js#6333.

**Comment by kumavis** [comment]
closing this for now, reopen if you think this is not solved.
