### ISSUE TITLE
Build will not load Three.js from prelude.js

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#5]
When running the examples, I get the following error:
Uncaught Error: Cannot find module '../Three'

The error is printed from browserify's prelude.js. The problem occurs in any module that attempts to require Three.js, such as Object3d. The relative path is correct.

**Comment by coballast** [comment]
I suspect this might have to do with the fact that we have circular requires between Three.js and any subsidiary objects that need to require constants in Three.js. Circular requires work fine inside a node.js environment as long as you plan ahead, but browserify might be another story.

An option would be to have the utility move everything that was originally defined in the top level THREE into a seperate ThreeGlobals module, and have everything require from that, including Three.js. That would eliminate the cycle and solve the problem.

**Comment by kumavis** [comment]
Thats a good hypothesis-- I would suggest more investigation before seeking a solution tho.
Hmmm... I'll dig for a moment as a morning warmup. Would love to be helping more with this but buried in another project for awhile...

**Comment by kumavis** [comment]
Can you list your browserify version and how you're running/opening the demos.

**Comment by kumavis** [comment]
I'm working off of `three.js#master`
When I convert + build three.js then run the `software_geometry_earth` demo I get:
`Uncaught TypeError: Object prototype may only be an Object or null: undefined`
which comes from
```js
OrthographicCamera.prototype = Object.create(Camera.prototype);
```
where `Camera.prototype` is undefined because
```js
require('./Camera') //=> Object {}
```

**Comment by kumavis** [comment]
I think you're on to something with the circular deps. And I agree with your suggested solution.

**Comment by coballast** [comment]
I'll make a branch and try it there.

**Comment by kumavis** [comment]
I poked a round for a bit -- awesome to see it happen! we're shifting and transforming years and years worth of human minds ticking away on this project. Behold the magic of Robotic Syntax Surgery!

**Comment by coballast** [comment]
I have a branch up that moves global THREE objects to seperate modules. After manually modifying the resulting src I got a build that doesn't get the original circular dependency errors.

**Comment by coballast** [comment]
However, I was running the webgl_camera demo and I got the exact same error you did. I think this is a separate/different problem.

**Comment by coballast** [comment]
I will make a seperate issue for that guy.

**Comment by coballast** [comment]
Unfortunately, I don't think this is going to be a completely automatic process. We may have to modify the output source code in order to get things to work a little bit (because writing code to do that would be harder). Personally I'm very satisfied with the way things are going so far. Most of the work has been effectively automated away.

**Comment by kumavis** [comment]
@coballast manual changes are ok for now, maybe we need to start recording the additional steps in the readme.
