### ISSUE TITLE
Undefined prototypes for various THREE objects.

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#9]
Some objects get exported as plain old objects in the final three.js build. This results in undefined prototype problems when inheritance is involved See issue #5 .

**Comment by coballast** [comment]
I set some breakpoints inside Camera.js. It looks like the code in it never even runs. require() doesn't touch it. Weird.

**Comment by coballast** [comment]
In the root Three.js file, everything from ThreeGlobals gets loaded fine. The error with OrthographicCamera comes when <b>Camera gets loaded into Three.js but before OrthographicCamera loads Camera</b>. Very strange. Browserify seems to be setting up the correct dependency graph after poking through the bundle, so this is going to keep me occupied for a while.

**Comment by coballast** [comment]
Note, I am working with r70 rather than dev due to #10

**Comment by coballast** [comment]
I believe I have found the problem. There is another circular dependency between Object3D and it's various subclasses.

**Comment by coballast** [comment]
I'm going to generate a visual graph depicting dependency relationships. I'm afraid this problem may be more widespread than I thought.

**Comment by kumavis** [comment]
@coballast I tried to generate one and the circ deps prevented it from working... tried hacking the lib to make it work anyways but failed. Was using https://github.com/conradz/browserify-graph

**Comment by kumavis** [comment]
posted some research on circ deps in the other issue https://github.com/coballast/threejs-browserify-conversion-utility/issues/10#issuecomment-80681888

**Comment by kumavis** [comment]
holy crap everything is so circular X_X
especially the math

Vector3 uses Matrix4 which uses Vector3

**Comment by kumavis** [comment]
Here's another:
`Box3 > BufferGeometry > Geometry > Sphere > Box3`

**Comment by kumavis** [comment]
the `Box3 > BufferGeometry` dep is stupid, its another case where things should be inverted. Instead of type checking Geometry types in Box3, and deciding what to do there, it should ask for `geometry.getVertices()` and Buffer geometry can implement this using its position array.
Bad practices all over the place.

**Comment by kumavis** [comment]
There's something discouraging about 135 open PRs

**Comment by kumavis** [comment]
plan B make a new three.js from scratch

**Comment by kumavis** [comment]
```
13:19 <kumavis> working on a project to automatically transform three.js to browserify
13:19 <kumavis> turns out three.js is full of circular deps
13:20 <kumavis> which works alright if you concat everything in the right order (like there currently build system does) but does not work so great in browserify
13:20 <kumavis> e.g. Vector3 requires Matrix4 which requires Vector3
13:21 <kumavis> if everything exports its reference before requiring anything else, this is okay
13:21 <kumavis> but that is not a common pattern, and particularly difficult in some cases
13:23 <kumavis> if you dont export before you import, Matrix4's reference to Vector3 will be an empty obj
13:25 <kumavis> another possibility is to run all requires just-in-time before usage.
13:26 <kumavis> if you have any suggestions, hacks...
13:32  → therealkoopa joined  ⇐ AvianPhone quit  ↔ thlorenz popped in  
14:01 <kumavis> the situation is exacerbated by the fact they're trying to use things immediately. e.g.: setting the module.exports for Matrix4 requires using Vector3
14:09 <kumavis> i imagine that their build system uses some kind of bogosort that if the build fails it tries another ordering : P
14:10  → peutetre and oncenull joined  ⇐ therealkoopa quit  ↔ phated_ popped in  ↔ phated nipped out  
14:23 <mikolalysenko> the only way to fix that situation is group the circular bits into a single module
14:23 <mikolalysenko> kumavis: ^^^
14:24 <substack> or make it so vec3 doesn't depend on mat4
14:24 <substack> just move the mat4 things out of vec3 and into mat4
14:24 <substack> that's what gl-vec3 and gl-mat4 do
14:25 <substack> and it's even easier if you pass around [x,y,z] data instead of instances
```

**Comment by coballast** [comment]
Circular dependencies are symptomatic of poor software design anyway. If we somehow get this into a state where everything works, I'm not optimistic that it will be accepted into the main repo.

**Comment by coballast** [comment]
If we just make a separate fork that we work on on our own, we are free to fix these and all sorts of other problems. The general feeling I get is that many developers have the same issues with the "official" codebase that we do. I'm confident there would be widespread support for such a fork.

**Comment by coballast** [comment]
Also, I hate mdcs. I tolerate it, but I would love an excuse to ditch it.

**Comment by coballast** [comment]
I think I'm going to go through the effort to get a pictorial graph up. People need to know about this horror.

**Comment by coballast** [comment]
It would also allow us to integrate glslify and other stack.gl components to simplify things even more. Quite frankly, we need a do-over from a small group of people away from the main source. When everyone has a working example that demonstrates that this is clearly the best way to go, everyone will follow swiftly. It should be super obvious that this is the best route, but for some reason it isn't, or it gets lost in the rabble.

**Comment by kumavis** [comment]
If you can produce a graph, I'd say go for it. I think that's some info that should be spread.
And I agree with your sentiments. I don't know about creating and maintaining a fork though. Sounds like it would be better to start a new lib by forking the scene-based api here https://github.com/mikolalysenko/gl-plot3d.

**Comment by kumavis** [comment]
If we do intend to abandon this conversion project, we should do a writeup of our findings. Your graph would be excellent there.

**Comment by coballast** [comment]
I have an interactive graph up <a target="_blank" href="http://jsbin.com/medezu/2/edit?html,js,output">here</a>.

I couldn't figure out how to generate a planar graph, so if you want a clearer picture you'll have to drag everything out yourself.

**Comment by coballast** [comment]
I created an issue: mrdoob/three.js#6241

**Comment by kumavis** [comment]
I think we can deal with the circular deps if we do the following:

1. change how we're exporting/requiring things.
```js
var Vector3 = require('./vector3.js')
```
not 
```js
var Vector3 = require('./vector3.js').Vector3
```
2. remove all cases where Class definitions immediately instantiate other Classes (e.g. making scratch `Vector3`s for math). e.g.:
```js
mathFn: (function(){
  var scratch = new Vector3([0,0,0])
  return function(a, b){
    scratch.set(a);
    scratch.plus(b);
    return scratch
  }
})()
```

**Comment by coballast** [comment]
@kumavis The first two changes are trivial modifications to the utility that I handle. The third one I have no clue about.

**Comment by kumavis** [comment]
Awesome! The third one should just be done via PRs against `upstream/dev`

**Comment by coballast** [comment]
Question: when having the exports prepended at the top of the file before requires, would I need to have the util set the variables to empty dummy objects of some kind?

In your example above, you are declaring Vector3 as a normal function which I think allows function hoisting to work, but the way I currently have it set up, Vector3 is a local variable assigned to a function object. I may have to change it to your form to get it to work.

Browserify wraps these things in closures though, so if I do change it I don't think it will cause any additional problems.

**Comment by kumavis** [comment]
I don't anticipate that to work. Lets look at the cycle `Vector3 -> Matrix4 -> Vector3`. It will start defining `Vector3`, and as soon as it hits the `require('./matrix4.js')` it will go over and start defining `Matrix4`. When it hits `require('./vector3.js')` in `Matrix4` it will immediately return the value of `Vector3`'s `module.exports` as it was at the point that it started defining `Matrix4`.

Words are hard, here's code:

```js
// multiple exports style
var Matrix4 = require('./matrix4.js').Matrix4;  // './vector3.js' will be {}, Vector3 will be undefined
module.exports.Vector3 = function Vector3(){ ... }
// Bad - Matrix4 has incorrect reference to Vector3
```

```js
// single export style
var Matrix4 = require('./matrix4.js');  //Vector3 will be {}
module.exports = function Vector3(){ ... }
// Bad - Matrix4 has incorrect reference to Vector3
```

```js
module.exports = {}
var Matrix4 = require('./matrix4.js');  //Vector3 will be {}
module.exports = function Vector3(){ ... }
// Bad - Matrix4 has incorrect reference to Vector3
```

```js
module.exports = function Vector3(){ ... }
var Matrix4 = require('./matrix4.js');  //Vector3 will be the correct class
// Good - Matrix4 has correct reference to Vector3
```
I think this is the best style:
```js
module.exports = Vector3;
var Matrix4 = require('./matrix4.js');  //Vector3 will be the correct class
// Good - Matrix4 has correct reference to Vector3
function Vector3(){ ... }
```

**Comment by kumavis** [comment]
playing with another style -- i prefer the hoisting style above tho
```js
var Vector3 = module.exports = function() { this._init() };
var Matrix4 = require('./matrix4.js');  //Vector3 will be the correct class

Vector3.prototype._init = function(){ /* anything that would have gone in the constructor */ }
Vector3.prototype.add = function(){  }
Vector3.prototype.sub = function(){  }

// Good - Matrix4 has correct reference to Vector3
```

**Comment by coballast** [comment]
Function hoisting it is then.

**Comment by coballast** [comment]
@kumavis I am working on function hoisting right now. It should be done very quickly.

You might also like to know that Matrix4 lazy-loads scratch vars. It's in upstream/dev. See mrdoob/three.js#6333

**Comment by coballast** [comment]
@kumavis Finished. There is a new problem in that local variables that aren't functions are assigned to exports before they are declared. I'll fix that asap.

**Comment by kumavis** [comment]
Awesome, reviewed the PR -- managing whitespace is a pain, eh? Can't wait until we evolve to compose ASTs directly instead of writing code

**Comment by coballast** [comment]
I feel like this issue has been effectively addressed by our cyclic dependency work on three.js. Therefore, I am closing it. We can simply reopen it if future builds demonstrate this behavior.
